#! /bin/sh

# Autostart programs
sxhkd &
xsetroot -cursor_name left_ptr &
polybar bspwm &
brightnessctl -s 30% &
feh --bg-scale /home/voidxs/Pictures/wallpapers/purple_landscape.jpg &
mpd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating manage=off
