#! /bin/sh

# Autostart programs
sxhkd &
xsetroot -cursor_name left_ptr &
polybar bspwm &
picom -b &
mpd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#5fafff"
bspc config urgent_border_color  "#bd2c40"

# Rules
bspc rule -a '*' follow=no
bspc rule -a firefox desktop='^2' follow=no
bspc rule -a Steam desktop='^1' follow=no state=floating
bspc rule -a mpv state=fullscreen
bspc rule -a feh state=floating
bspc rule -a discord desktop='^4' follow=no
bspc rule -a Galculator state=floating

~/.config/bspwm/autostart
bspc config external_rules_command ~/.config/bspwm/external_rules
