#! /bin/sh

# Autostart programs
sxhkd &
xsetroot -cursor_name left_ptr &
polybar bspwm &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#0a6cf5"
bspc config urgent_border_color  "#bd2c40"

# Rules
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
